2018-11-04 15:38:59,534 ERROR: Exception on /group/TEST [GET] [in d:\serialshow\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\serialshow\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\serialshow\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\rfid-signin-python\app\routes.py", line 229, in group
    time_student_id=student.student_id).all()
NameError: name 'student' is not defined
2018-11-04 15:39:20,638 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-04 15:42:22,343 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-04 15:42:24,353 ERROR: Exception on /group/TEST [GET] [in d:\serialshow\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\serialshow\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\serialshow\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\serialshow\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\rfid-signin-python\app\routes.py", line 236, in group
    for i in range(len(rows)):
NameError: name 'rows' is not defined
2018-11-04 15:42:44,767 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-04 15:43:09,554 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:47:14,808 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:48:53,156 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:50:56,759 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:53:13,505 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:53:53,006 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:54:52,319 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:55:31,295 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:56:39,964 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 14:58:38,644 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 15:03:11,033 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
2018-11-05 15:03:25,949 INFO: Serialshow startup [in D:\serialshow\rfid-signin-python\app\__init__.py:30]
