2018-10-20 21:38:09,808 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-20 21:41:52,227 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-20 21:43:08,012 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-20 22:04:27,887 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:52:57,614 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:54:39,777 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:55:58,379 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:56:05,056 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:57:58,074 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 08:58:00,652 ERROR: Exception on /signin [GET] [in c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\app\routes.py", line 113, in signin
    return jsonify(name=student.student_name.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
2018-10-21 08:59:32,785 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 09:12:53,242 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 09:35:57,806 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
2018-10-21 09:36:54,870 ERROR: Exception on /signin [GET] [in c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\app\routes.py", line 102, in signin
    curr_class = Class.query.filter_by(class_token=current_user.class_token).first_or_404()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'class_token'
2018-10-21 09:37:14,371 ERROR: Exception on /signin [GET] [in c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\app\routes.py", line 102, in signin
    curr_class = Class.query.filter_by(class_token=current_user.class_token).first_or_404()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'class_token'
2018-10-21 09:38:24,041 ERROR: Exception on /signin [GET] [in c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\app\routes.py", line 102, in signin
    curr_class = Class.query.filter_by(class_token=current_user.class_token).first_or_404()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'class_token'
2018-10-21 09:39:44,815 ERROR: Exception on /signin [GET] [in c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\serialshow\app\routes.py", line 102, in signin
    curr_class = Class.query.filter_by(class_token=current_user.class_token).first_or_404()
  File "c:\users\q\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'class_token'
2018-10-21 09:43:46,134 INFO: Serialshow startup [in D:\serialshow\app\__init__.py:28]
